=begin pod

=head1 NAME

Shareable - Provides a parent class with shareable and semi-persistent state

=head1 SYNOPSIS

=begin code :lang<raku>

use Shareable;

=end code

=head1 DESCRIPTION

Shareable is ...

=head1 AUTHOR

Tom Browder <tbrowder@acm.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2021 Tom Browder

This library is free software; you may redistribute it or modify it under the Artistic License 2.0.

=end pod
